# Generated by Django 3.2.7 on 2021-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
